### ISSUE TITLE
Make the extension work with remote development

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1432]
We need to make the extension work with remote development to do this we need to do:

- [x] fix grpc
- [x] update minimum version of vscode
- [x] add to readme about the error
- [ ] fix file dialogs (vscode has an inbuilt version of fs)

**Comment by cazfletch** [comment]
Just doing ssh types of remote development
