### ISSUE TITLE
Enable high level go support in the extension

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#1645]
Like with node and java we need to support Go

- [ ] Support go contract api
- [ ] Be able to generate go functional tests
- [ ] Be able to debug a high level go contract
