### ISSUE TITLE
As a developer i want to create java smart contracts

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#520]
A developer can use the extension with java

Possible list of things needed: 
- [x] Generate java tests
- [x] Submit transactions
- [x] generate smart contract
- [x] update tutorial
- [ ] Packaging should run gradle build - not doing as won't run tests on instantiate anymore

**Comment by mbwhite** [comment]
- I've an update to the generator to provide a Java contract project. This worked in testing without modifications to the extensions
- Submitting and evaluation of transactions was working without any required changes - if any changes do have to be made this could be indicative of a defect in the SDK and or Chaincode shim
- The extension needs to be able to parse the `build.gradle` and `gradle.settings` to get version and name.. or the pom.xml in the case of maven builds.

**Comment by mbwhite** [comment]
Updated the generator to use the newly published 1.4.2 Fabric Java Contract code
https://github.com/IBM-Blockchain/generator-fabric/pull/141

Also put in a request to update the dev tutorial here..
https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/1165
