### ISSUE TITLE
support fabric 2

### ISSUE THREAD

**Issue by cazfletch** [IBM-Blockchain/blockchain-vscode-extension#741]
Here is the broad approach to supporting Fabric 2.0

1.  We’ll start a new GitHub branch of the extension that’s just for 2.0 

2. Therefore there will be a branch of the extension for Fabric v1 and a branch for v2

3. The v1 branch will remain the one “released to the Marketplace” to start with

4. Meanwhile, we’ll be getting the v2 branch all spick and span, and encouraging anyone who wants to try it out (we’ll have a VSIX available from Git)

5. At some point, when we’re fairly confident the v2 one is #goodEnough we’ll “flip the switch” and have the v2 branch be the one that publishes to Marketplace

6. At that point, anyone who wants to continue working with Fabric v1 will need to explicitly install an older version of the extension

7. Any serious issues  found with the v1 dev tools, we can fix in that branch and guide them to install from VSIX to get a version with the fix

**Comment by caroline-church** [comment]
Tried a 2.0 version of fabric with 1.4 images and this all worked ok. I also spoke to Andy Coleman who mentioned that the wallet format might change which could cause a problem with using 1.4 wallets with 2.0 but this isn't a definite thing that will be done. The only other problem could be that the format of errors but this might not go in either

**Comment by cazfletch** [comment]
Questions
 - [ ] Will fabric network/ fabric client/ fabric ca 2.0 support talking to a 1.4 runtime
 - [ ] is there a way to tell whether a fabric is using the new life cycle or old life cycle from the sdk?
          https://fabric-sdk-node.github.io/master/Channel.html#getChannelConfig__anchor is how to get it but you have to decode the block info
- [ ] if i have the Application capabilities at 1.4 and you instantiate some chaincode, then you upgrade the config to have the capabilities set at 2.0. Would i call `getNamspaceDefinitions()` to get the chaincode or `queryInstantiatedChaincode()`
    - Answer from Alessandro - you still need to query the lifecycle that was used to install/instantiate the chaincode in the first place, but the idea is that as you upgrade to 2.0, you should also re-define your chaincodes in the new lifecycle, at which point, you can direct all queries to the new lifecycle

**Comment by EdMoffatt** [comment]
Gonna split design work between myself and Charlotte - here's a list to track what we're working on, and we'll update with designs as we have them!

Things needed to make local fabric support fabric 2.0
- [ ] Update generator to generate projects at either version 1.4 or 2.0 (CM)
- [ ] Add ability to start fabric at either 1.4 or 2.0 (EPJ)

Things needed to support new chaincode life cycle
- [ ] When packaging ask if you want to create a package for 1.4 or 2.0 (CM)
- [ ] We need to store a chaincode object somewhere as you install on a chaincode object and then this needs to be passed to the approve and commit stage (EPJ??)
- [ ] update command flows for new process (CM??)
- [ ] update the local fabric ops view to not say instantiate if it 2.0 (EPJ)
- [ ] might need to up the request timeout when submitting the first transaction as this is when the chaincode container starts (CM??)
- [ ] need to keep track of sequence number some how as need to increment it when upgrade (although not called upgrade anymore have to go through same steps as new chaincode) (EPJ??)

**Comment by Charlotte8699** [comment]
**Determining the version of a packaged project.**

The process is much the same as it is presently, but I have suggested asking the user which version they would like to package their files at before packaging them. 
I have also left the final page the same as it is now, but the work Ed is doing on deciding how to display different versions will lead to this page changing.

https://xd.adobe.com/view/5014483d-c951-4d06-58a2-a17cd9b21cf7-2625/

Notes on packaging from Jake for reference:
- Contents of the package remain the same, the file gets packaged as a .zip instead of a .cds.
- Projects should package at any version regardless of where the files were created.
- Question: Is the user-provided metadata different?

I will update this comment as this progresses.

**Comment by siddjain** [comment]
what is the ETA for supporting Fabric 2.0?
